name: Deployment Actions

on: deployment_status

jobs:
  browser_e2e:
    # Only want to run on success, otherwise it might be "pending", or "failure". Test
    if: ${{ (github.event.deployment_status.state == 'success') }}
    name: Browser E2E Eng
    runs-on: ubuntu-latest

    steps:
      - name: run Playwright
        id: run_playwright
        run: npm run playwright:test:ci
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
